server:
    port : 5000

spring:
    cache:
        caffeine:
            spec: expireAfterWrite=5s
    profiles:
        active: '@spring.profiles.active@'

resilience:
    slidingWindowSize: 10
    waitDurationInOpenState: 5
    minimumNumberOfCalls: 5
    failureRateThreshold: 50.0

external:
    product:
        service:
            url: http://localhost:3001
