server:
    port : 5000

spring:
    cache:
        caffeine:
            spec: expireAfterWrite=5s
    profiles:
        active: '@spring.profiles.active@'


external:
    product:
        service:
            url: http://localhost:3001
